# Generated by Django 6.0.5 on 2026-06-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_creditaccount_creditrecord_payment_delete_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('FONEPAY', 'FonePay'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('CREDIT', 'Credit')], max_length=20),
        ),
    ]
