# Generated by Django 6.0.5 on 2026-06-02 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='table',
            name='number',
        ),
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
        migrations.AddField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
