# Generated by Django 6.0.5 on 2026-06-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ORDER', 'Order'), ('PAYMENT', 'Payment'), ('SHIFT', 'Shift'), ('REPORT', 'Report')], max_length=20)),
                ('action', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
